// Historical V1 URLs retained as explicit, non-functional V2 migration contracts.
// Source: reference/legacy-v3/src/docs/openapi.ts at commit 8adcb5a.
// Training is intentionally excluded because that domain was removed from V2 scope.
export const legacyV1RouteContracts = [
  { method: 'get', path: '/login-history', tag: 'Login History' },
  { method: 'get', path: '/administration/login-history', tag: 'Login History' },
  { method: 'get', path: '/notifications/compliance-reminders', tag: 'Policies' },
  { method: 'patch', path: '/notifications/compliance-reminders/{notificationId}/read', tag: 'Policies' },
  { method: 'get', path: '/incidents', tag: 'Incidents' },
  { method: 'post', path: '/incidents', tag: 'Incidents' },
  { method: 'get', path: '/incidents/mine', tag: 'Incidents' },
  { method: 'get', path: '/incidents/{incidentId}', tag: 'Incidents' },
  { method: 'patch', path: '/incidents/{incidentId}/severity', tag: 'Incidents' },
  { method: 'get', path: '/incidents/assignment-options', tag: 'Incidents' },
  { method: 'patch', path: '/incidents/{incidentId}/assignee', tag: 'Incidents' },
  { method: 'patch', path: '/incidents/{incidentId}/progress', tag: 'Incidents' },
  { method: 'get', path: '/incidents/{incidentId}/evidence', tag: 'Incidents' },
  { method: 'post', path: '/incidents/{incidentId}/evidence', tag: 'Incidents' },
  { method: 'get', path: '/incidents/evidence/{evidenceId}/download', tag: 'Incidents' },
  { method: 'delete', path: '/incidents/evidence/{evidenceId}', tag: 'Incidents' },
  { method: 'post', path: '/users/{userId}/lock', tag: 'Users' },
  { method: 'post', path: '/users/{userId}/unlock', tag: 'Users' },
  { method: 'post', path: '/admin/users/{userId}/lock', tag: 'Users' },
  { method: 'post', path: '/admin/users/{userId}/unlock', tag: 'Users' },
  { method: 'post', path: '/ai-alerts/{alertId}/false-positive', tag: 'AI Alerts' },
  { method: 'get', path: '/access-control/permissions', tag: 'Role Management' },
  { method: 'get', path: '/access-control/roles', tag: 'Role Management' },
  { method: 'post', path: '/access-control/roles', tag: 'Role Management' },
  { method: 'get', path: '/access-control/roles/{roleId}', tag: 'Role Management' },
  { method: 'patch', path: '/access-control/roles/{roleId}', tag: 'Role Management' },
  { method: 'delete', path: '/access-control/roles/{roleId}', tag: 'Role Management' },
  { method: 'post', path: '/auth/password-reset/request', tag: 'Authentication' },
  { method: 'post', path: '/auth/change-password', tag: 'Authentication' },
  { method: 'post', path: '/auth/mfa/setup', tag: 'Authentication' },
  { method: 'post', path: '/auth/mfa/verify', tag: 'Authentication' },
  { method: 'post', path: '/auth/mfa/challenge/verify', tag: 'Authentication' },
  { method: 'post', path: '/auth/mfa/disable', tag: 'Authentication' },
  { method: 'post', path: '/auth/mfa/recovery-requests', tag: 'Authentication' },
  { method: 'get', path: '/admin/mfa-recovery-requests', tag: 'MFA Recovery Administration' },
  { method: 'post', path: '/admin/mfa-recovery-requests/{requestId}/approve', tag: 'MFA Recovery Administration' },
  { method: 'post', path: '/admin/mfa-recovery-requests/{requestId}/reject', tag: 'MFA Recovery Administration' },
  { method: 'post', path: '/auth/password-reset/confirm', tag: 'Authentication' },
  { method: 'get', path: '/users', tag: 'Users' },
  { method: 'post', path: '/users', tag: 'Users' },
  { method: 'get', path: '/users/{userId}', tag: 'Users' },
  { method: 'patch', path: '/users/{userId}', tag: 'Users' },
  { method: 'delete', path: '/users/{userId}', tag: 'Users' },
  { method: 'post', path: '/users/{userId}/deactivate', tag: 'Users' },
  { method: 'post', path: '/users/{userId}/roles', tag: 'Users' },
  { method: 'get', path: '/users/assignable-roles', tag: 'Users' },
  { method: 'get', path: '/users/create-options', tag: 'Users' },
  { method: 'post', path: '/risks', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks/create-options', tag: 'Risk Assessments' },
  { method: 'patch', path: '/risks/{riskAssessmentId}', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks/{riskAssessmentId}', tag: 'Risk Assessments' },
  { method: 'post', path: '/risks/{riskAssessmentId}/cancel', tag: 'Risk Assessments' },
  { method: 'patch', path: '/risks/{riskAssessmentId}/residual-assessment', tag: 'Risk Assessments' },
  { method: 'post', path: '/risks/treatment-plans', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks/treatment-plans', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks/treatment-plans/create-options', tag: 'Risk Assessments' },
  { method: 'patch', path: '/risks/treatment-plans/{treatmentPlanId}', tag: 'Risk Assessments' },
  { method: 'get', path: '/risks/treatment-plans/{treatmentPlanId}', tag: 'Risk Assessments' },
  { method: 'post', path: '/risks/treatment-plans/{treatmentPlanId}/cancel', tag: 'Risk Assessments' },
  { method: 'patch', path: '/risks/treatment-plans/{treatmentPlanId}/actions/{actionId}/progress', tag: 'Risk Assessments' },
  { method: 'post', path: '/risks/treatment-plans/{treatmentPlanId}/submit', tag: 'Risk Assessments' },
  { method: 'post', path: '/risks/treatment-plans/{treatmentPlanId}/approve', tag: 'Risk Assessments' },
  { method: 'post', path: '/assets', tag: 'Assets' },
  { method: 'get', path: '/assets', tag: 'Assets' },
  { method: 'get', path: '/assets/create-options', tag: 'Assets' },
  { method: 'get', path: '/assets/import-template', tag: 'Assets' },
  { method: 'get', path: '/assets/export', tag: 'Assets' },
  { method: 'post', path: '/assets/import', tag: 'Assets' },
  { method: 'get', path: '/assets/imports/{importJobId}', tag: 'Assets' },
  { method: 'get', path: '/assets/{assetId}', tag: 'Assets' },
  { method: 'patch', path: '/assets/{assetId}', tag: 'Assets' },
  { method: 'delete', path: '/assets/{assetId}', tag: 'Assets' },
  { method: 'post', path: '/assets/{assetId}/classify-criticality', tag: 'Assets' },
  { method: 'put', path: '/assets/{assetId}/owner', tag: 'Assets' },
  { method: 'get', path: '/assets/{assetId}/history', tag: 'Assets' },
  { method: 'post', path: '/compliance/policies', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/drafts/reviewable', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/{policyId}/versions/{versionId}/review', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/published/mine', tag: 'Policy Compliance' },
  { method: 'get', path: '/compliance/policy-control-mappings', tag: 'Policies' },
  { method: 'get', path: '/compliance/frameworks', tag: 'Policies' },
  { method: 'get', path: '/compliance/frameworks/{frameworkId}/controls', tag: 'Policies' },
  { method: 'put', path: '/compliance/policies/{policyId}/versions/{versionId}/frameworks/{frameworkId}/control-mappings', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/department-assignments', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/acknowledgements/mine', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/{policyId}/versions/{versionId}/acknowledgement', tag: 'Policies' },
  { method: 'post', path: '/compliance/policies/{policyId}/versions/{versionId}/acknowledgements', tag: 'Policies' },
  { method: 'put', path: '/compliance/policies/{policyId}/departments', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/{policyId}/drafts/{versionId}', tag: 'Policies' },
  { method: 'patch', path: '/compliance/policies/{policyId}/drafts/{versionId}', tag: 'Policies' },
  { method: 'get', path: '/security-monitoring/log-sources', tag: 'Security Monitoring' },
  { method: 'post', path: '/security-monitoring/log-sources', tag: 'Security Monitoring' },
  { method: 'get', path: '/ai-alerts/thresholds', tag: 'AI Alerts' },
  { method: 'put', path: '/ai-alerts/thresholds/{assetId}', tag: 'AI Alerts' },
  { method: 'get', path: '/ai-alerts/models', tag: 'AI Alerts' },
  { method: 'post', path: '/ai-alerts/models', tag: 'AI Alerts' },
  { method: 'get', path: '/ai-alerts/{alertId}/explanation', tag: 'AI Alerts' },
  { method: 'post', path: '/ai-alerts/models/{modelVersionId}/activate', tag: 'AI Alerts' },
  { method: 'post', path: '/compliance/policies/{policyId}/versions/{versionId}/publish', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/version-history', tag: 'Policies' },
  { method: 'get', path: '/compliance/policies/{policyId}/versions/{versionId}/history', tag: 'Policies' },
  { method: 'post', path: '/compliance/policies/{policyId}/versions', tag: 'Policies' },
  { method: 'get', path: '/compliance/control-assessments', tag: 'Policies' },
  { method: 'get', path: '/compliance/controls/{controlId}/assessments', tag: 'Policies' },
  { method: 'post', path: '/compliance/controls/{controlId}/assessments', tag: 'Policies' },
  { method: 'get', path: '/compliance/evidence/assessments', tag: 'Policies' },
  { method: 'post', path: '/compliance/control-assessments/{assessmentId}/evidence', tag: 'Policies' },
  { method: 'get', path: '/compliance/evidence/{evidenceId}/download', tag: 'Policies' },
  { method: 'patch', path: '/security-monitoring/log-sources/{logSourceId}', tag: 'Security Monitoring' },
  { method: 'delete', path: '/security-monitoring/log-sources/{logSourceId}', tag: 'Security Monitoring' },
  { method: 'post', path: '/integrations', tag: 'Integrations' },
  { method: 'get', path: '/integrations', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}', tag: 'Integrations' },
  { method: 'patch', path: '/integrations/{id}', tag: 'Integrations' },
  { method: 'get', path: '/integrations/monitoring/connection-status', tag: 'Integrations' },
  { method: 'post', path: '/integrations/monitoring/check-all', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/connection-status', tag: 'Integrations' },
  { method: 'post', path: '/integrations/{id}/test-connection', tag: 'Integrations' },
  { method: 'post', path: '/security-monitoring/log-sources/{logSourceId}/events', tag: 'Security Monitoring' },
  { method: 'post', path: '/integrations/{id}/schedules', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/schedules', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/schedules/{scheduleId}', tag: 'Integrations' },
  { method: 'patch', path: '/integrations/{id}/schedules/{scheduleId}', tag: 'Integrations' },
  { method: 'delete', path: '/integrations/{id}/schedules/{scheduleId}', tag: 'Integrations' },
  { method: 'post', path: '/integrations/{id}/sync', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/sync-jobs', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/sync-jobs/{jobId}', tag: 'Integrations' },
  { method: 'get', path: '/integrations/logs/stats', tag: 'Integrations' },
  { method: 'get', path: '/integrations/logs', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/logs', tag: 'Integrations' },
  { method: 'post', path: '/integrations/{id}/api-keys', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/api-keys', tag: 'Integrations' },
  { method: 'get', path: '/integrations/{id}/api-keys/{keyId}', tag: 'Integrations' },
  { method: 'patch', path: '/integrations/{id}/api-keys/{keyId}', tag: 'Integrations' },
  { method: 'post', path: '/integrations/{id}/api-keys/{keyId}/rotate', tag: 'Integrations' },
  { method: 'post', path: '/integrations/{id}/api-keys/{keyId}/revoke', tag: 'Integrations' },
] as const;
