import ExcelJS from 'exceljs';
import { PNG } from 'pngjs';

type Metadata = {
  schemaVersion: string; exportId: string; title: string; generatedAt: string;
  displayTimeZone: string; exportedBy: { id: string; name: string; email: string; role: string };
  purpose: string; scope: string; format: string; recordCount: number;
  sourceSystem: string; sourceDataset: string; recordSetSha256: string;
};
type Row = {
  id: string; occurredAt: string; eventType: string; source: string; sourceIp: string | null;
  actor: string; actorEmail: string | null; actorType: string; status: string;
  resourceType: string; resourceId: string | null; correlationId: string | null;
  errorCode: string | null; durationMs: number | null;
};

const blue = '1769F6';
const navy = '101B3F';
const muted = '60708F';
const pale = 'F3F7FE';
const border = 'DFE6F2';

export async function renderInvestigationLogXlsx(
  metadata: Metadata,
  filters: Record<string, unknown>,
  rows: Row[],
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = metadata.exportedBy.name;
  workbook.lastModifiedBy = metadata.exportedBy.name;
  workbook.company = 'SecuraAI';
  workbook.created = new Date(metadata.generatedAt);
  workbook.modified = new Date(metadata.generatedAt);
  workbook.subject = metadata.purpose;
  workbook.title = metadata.title;
  workbook.description = 'Chain-of-custody investigation log export generated by SecuraAI.';

  const report = workbook.addWorksheet('Investigation Report', { views: [{ showGridLines: false }] });
  report.properties.defaultRowHeight = 18;
  report.mergeCells('A1:A2');
  report.mergeCells('B1:O1');
  report.getCell('B1').value = 'SECURAAI · INVESTIGATION LOG EXPORT';
  report.getCell('B1').font = { bold: true, size: 18, color: { argb: navy } };
  report.getCell('B1').alignment = { vertical: 'middle' };
  report.getRow(1).height = 27;
  report.getRow(2).height = 21;
  const imageId = workbook.addImage({ base64: `data:image/png;base64,${createLogoPng().toString('base64')}`, extension: 'png' });
  report.addImage(imageId, { tl: { col: 0, row: 0 }, ext: { width: 34, height: 34 } });
  report.mergeCells('B2:O2');
  report.getCell('B2').value = 'Evidence export · content hash is returned in the response headers and audit record';
  report.getCell('B2').font = { italic: true, size: 10, color: { argb: muted } };
  report.getCell('B2').alignment = { vertical: 'middle' };

  const metadataRows: Array<[string, string]> = [
    ['Schema version', metadata.schemaVersion], ['Export ID', metadata.exportId],
    ['Generated at (UTC)', metadata.generatedAt], ['Display time zone', metadata.displayTimeZone],
    ['Exported by', metadata.exportedBy.name], ['Exporter email', metadata.exportedBy.email],
    ['Exporter role', metadata.exportedBy.role], ['Purpose', metadata.purpose],
    ['Scope', metadata.scope], ['Source', `${metadata.sourceSystem} · ${metadata.sourceDataset}`],
    ['Record count', String(metadata.recordCount)], ['Record-set SHA-256', metadata.recordSetSha256],
  ];
  report.getCell('A4').value = 'EXPORT METADATA';
  styleSection(report.getCell('A4'));
  metadataRows.forEach(([label, value], index) => {
    const row = 5 + index;
    report.getCell(`A${row}`).value = label;
    report.getCell(`A${row}`).font = { bold: true, size: 9, color: { argb: muted } };
    report.mergeCells(`B${row}:O${row}`);
    report.getCell(`B${row}`).value = value;
    report.getCell(`B${row}`).font = { size: 9, color: { argb: navy } };
  });
  const filterRow = 18;
  report.getCell(`A${filterRow}`).value = 'APPLIED FILTERS';
  styleSection(report.getCell(`A${filterRow}`));
  report.mergeCells(`B${filterRow}:O${filterRow}`);
  report.getCell(`B${filterRow}`).value = Object.keys(filters).length ? JSON.stringify(filters) : 'No filters applied';
  report.getCell(`B${filterRow}`).font = { size: 9, color: { argb: navy } };

  const headerRow = 20;
  const headers = ['Log ID', 'Occurred (UTC)', 'Occurred (local)', 'Event type', 'Source', 'Source IP', 'Actor', 'Actor email', 'Actor type', 'Status', 'Resource type', 'Resource ID', 'Correlation ID', 'Error code', 'Duration (ms)'];
  report.getRow(headerRow).values = headers;
  report.getRow(headerRow).eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFF' }, size: 9 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: blue } };
    cell.alignment = { vertical: 'middle', wrapText: true };
    cell.border = thinBorder();
  });
  rows.forEach((item) => {
    const row = report.addRow([item.id, item.occurredAt, formatLocal(item.occurredAt), item.eventType, item.source, item.sourceIp ?? '', item.actor, item.actorEmail ?? '', item.actorType, item.status, item.resourceType, item.resourceId ?? '', item.correlationId ?? '', item.errorCode ?? '', item.durationMs ?? '']);
    row.eachCell((cell) => { cell.border = thinBorder(); cell.alignment = { vertical: 'top', wrapText: true }; cell.font = { size: 9, color: { argb: navy } }; });
    row.getCell(10).font = { bold: true, size: 9, color: { argb: item.status === 'SUCCESS' ? '159455' : 'C27208' } };
  });
  report.autoFilter = { from: `A${headerRow}`, to: `O${Math.max(headerRow, report.rowCount)}` };
  report.views = [{ state: 'frozen', ySplit: headerRow, showGridLines: false }];
  report.columns = [12, 24, 24, 22, 18, 18, 22, 28, 15, 14, 20, 38, 38, 18, 14].map((width) => ({ width }));
  report.headerFooter.oddFooter = '&LConfidential · SecuraAI&RPage &P of &N';
  report.pageSetup = { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0, paperSize: 9 };

  const custody = workbook.addWorksheet('Chain of Custody', { views: [{ showGridLines: false }] });
  custody.columns = [{ header: 'Event', key: 'event', width: 22 }, { header: 'Timestamp (UTC)', key: 'timestamp', width: 28 }, { header: 'Actor', key: 'actor', width: 24 }, { header: 'Email', key: 'email', width: 30 }, { header: 'Role', key: 'role', width: 20 }, { header: 'Export ID', key: 'exportId', width: 40 }, { header: 'Record count', key: 'count', width: 14 }, { header: 'Record-set SHA-256', key: 'hash', width: 68 }];
  custody.addRow({ event: 'EXPORT_GENERATED', timestamp: metadata.generatedAt, actor: metadata.exportedBy.name, email: metadata.exportedBy.email, role: metadata.exportedBy.role, exportId: metadata.exportId, count: metadata.recordCount, hash: metadata.recordSetSha256 });
  custody.getRow(1).eachCell((cell) => { cell.font = { bold: true, color: { argb: 'FFFFFF' } }; cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: blue } }; });
  custody.getRow(2).eachCell((cell) => { cell.border = thinBorder(); cell.alignment = { wrapText: true, vertical: 'top' }; });
  custody.mergeCells('A4:H4');
  custody.getCell('A4').value = 'Integrity note: verify the Content-SHA256 response header against the downloaded workbook bytes.';
  custody.getCell('A4').font = { italic: true, color: { argb: muted } };
  custody.views = [{ state: 'frozen', ySplit: 1, showGridLines: false }];
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

function styleSection(cell: ExcelJS.Cell) {
  cell.font = { bold: true, size: 10, color: { argb: blue } };
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: pale } };
}
function thinBorder(): Partial<ExcelJS.Borders> {
  return { top: { style: 'thin', color: { argb: border } }, bottom: { style: 'thin', color: { argb: border } }, left: { style: 'thin', color: { argb: border } }, right: { style: 'thin', color: { argb: border } } };
}
function formatLocal(value: string) {
  return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', timeZone: 'Asia/Ho_Chi_Minh', hour12: false }).format(new Date(value));
}
function createLogoPng() {
  const size = 128; const png = new PNG({ width: size, height: size });
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const corner = (x < 18 || x >= 110) && (y < 18 || y >= 110);
    const inCorner = corner && ((x < 18 ? 18 - x : x - 109) ** 2 + (y < 18 ? 18 - y : y - 109) ** 2 > 18 ** 2);
    const offset = (y * size + x) << 2; png.data[offset] = 23; png.data[offset + 1] = 105; png.data[offset + 2] = 246; png.data[offset + 3] = inCorner ? 0 : 255;
  }
  drawLine(png, 32, 25, 96, 25); drawLine(png, 96, 25, 92, 67); drawLine(png, 92, 67, 64, 101); drawLine(png, 64, 101, 36, 67); drawLine(png, 36, 67, 32, 25);
  return PNG.sync.write(png);
}
function drawLine(png: PNG, x0: number, y0: number, x1: number, y1: number) {
  const dx = Math.abs(x1 - x0); const sx = x0 < x1 ? 1 : -1; const dy = -Math.abs(y1 - y0); const sy = y0 < y1 ? 1 : -1; let error = dx + dy;
  while (true) { for (let ox = -2; ox <= 2; ox++) for (let oy = -2; oy <= 2; oy++) { const x = x0 + ox; const y = y0 + oy; if (x >= 0 && y >= 0 && x < png.width && y < png.height) { const i = (y * png.width + x) << 2; png.data[i] = 255; png.data[i + 1] = 255; png.data[i + 2] = 255; png.data[i + 3] = 255; } } if (x0 === x1 && y0 === y1) break; const e2 = 2 * error; if (e2 >= dy) { error += dy; x0 += sx; } if (e2 <= dx) { error += dx; y0 += sy; } }
}
