import { AppError } from '../../common/errors/app-error.js';
import { assetsRepository } from './assets.repository.js';
import type { ListAssetsQuery } from './dto/list-assets.dto.js';
async function activeActor(userId: string) { const actor = await assetsRepository.findActor(userId); if (!actor || actor.status !== 'ACTIVE') throw new AppError(401, 'UNAUTHORIZED', 'Authentication required'); return actor; }
const person = (item: { id: string; full_name: string; status: string } | null) => item ? { id: item.id, fullName: item.full_name, inactive: item.status !== 'ACTIVE' } : null;
export const assetsService = {
  async list(userId: string, query: ListAssetsQuery) { const actor = await activeActor(userId); const scopedQuery = actor.role === 'SECURITY_OFFICER' ? query : { ...query, ownerUserId: userId }; const [total, records] = await assetsRepository.list(scopedQuery); return { items: records.map((item) => ({ id: item.id, assetCode: item.asset_code, name: item.name, assetType: item.asset_type, criticality: item.criticality, dataClassification: item.data_classification, description: item.description, status: item.status.toLowerCase(), owner: person(item.users_assets_owner_user_idTousers), businessService: item.business_services ? { id: item.business_services.id, name: item.business_services.name, inactive: item.business_services.status !== 'ACTIVE' } : null, createdAt: item.created_at, updatedAt: item.updated_at })), pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; },
  async get(userId: string, assetId: string) { const actor = await activeActor(userId); const item = await assetsRepository.findById(assetId); if (!item) throw new AppError(404, 'ASSET_NOT_FOUND', 'Asset not found'); if (actor.role !== 'SECURITY_OFFICER' && item.owner_user_id !== userId) throw new AppError(403, 'FORBIDDEN', 'Asset Owner access required'); return {
    id: item.id, assetCode: item.asset_code, name: item.name, assetType: item.asset_type, criticality: item.criticality, dataClassification: item.data_classification, description: item.description, status: item.status.toLowerCase(), archivedAt: item.archived_at,
    owner: person(item.users_assets_owner_user_idTousers), createdBy: person(item.users_assets_created_byTousers), businessService: item.business_services ? { id: item.business_services.id, name: item.business_services.name, inactive: item.business_services.status !== 'ACTIVE' } : null,
    dependencies: item.asset_dependencies_asset_dependencies_asset_idToassets.map((link) => ({ id: link.id, type: link.dependency_type, description: link.description, asset: { id: link.assets_asset_dependencies_depends_on_asset_idToassets.id, assetCode: link.assets_asset_dependencies_depends_on_asset_idToassets.asset_code, name: link.assets_asset_dependencies_depends_on_asset_idToassets.name, status: link.assets_asset_dependencies_depends_on_asset_idToassets.status.toLowerCase() } })),
    controls: item.control_asset_links.map(({ security_controls: control }) => ({ id: control.id, code: control.control_code, name: control.name, implementationStatus: control.implementation_status.toLowerCase() })),
    eventSources: item.asset_event_sources.map(({ event_sources: source }) => ({ id: source.id, name: source.name, sourceType: source.source_type, status: source.status.toLowerCase() })),
    risks: item.risk_assets.map(({ risks: risk }) => ({ id: risk.id, code: risk.risk_code, title: risk.title, status: risk.status.toLowerCase() })),
    incidents: item.incident_assets.map(({ incidents: incident }) => ({ id: incident.id, code: incident.incident_code, title: incident.title, severity: incident.severity, status: incident.status.toLowerCase() })),
    createdAt: item.created_at, updatedAt: item.updated_at,
  }; },
};
